# --- CONFIG FINALE BINGX FUTURES x5 ---
USE_SPOT = False  # On coupe le spot
USE_FUTURES = True
FUTURES_AMOUNT_USDT = 10  # Tes 10$ en Futures USDT-M
LEVERAGE = 5
MARGIN_MODE = "ISOLATED"
SYMBOL_FUTURES = "BTC/USDT:USDT"
TP_PERCENT = 2.0
SL_PERCENT = 1.5