name: FYLHOMENTAL HYBRID

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install ccxt pandas

      - name: Run Meme SPOT
        env:
          BINGX_API_KEY: ${{ secrets.BINGX_API_KEY }}
          BINGX_SECRET_KEY: ${{ secrets.BINGX_SECRET_KEY }}
        run: python bot_meme.py

      - name: Run FYLHO PERP UNIVERSAL
        env:
          BINGX_API_KEY: ${{ secrets.BINGX_API_KEY }}
          BINGX_SECRET_KEY: ${{ secrets.BINGX_SECRET_KEY }}
        run: python bot_fylho_perp.py